compatibility_date = "2022-05-20"
kv_namespaces = [
  {binding = "POOLS", id = "5a8e602223d7498ea994f75dc1b87cd7", preview_id = "a9ba224f11d14dcda0534c36de408fa4" },
]
r2_buckets = [
  { binding = "SUBGRAPH_POOLS", bucket_name = "subgraph-pools-dev", preview_bucket_name = "subgraph-pools-dev" }
]
main = "src/index.ts"
name = "routing-dev"
node_compat = true
[triggers]
crons = ["0 0 * * *"]

[env.production]
kv_namespaces = [
  {binding = "POOLS", id = "8d9dd27cc21f47a2b319167bd65632e6"},
]
r2_buckets = [
  { binding = "SUBGRAPH_POOLS", bucket_name = "subgraph-pools", preview_bucket_name = "subgraph-pools-dev" }
]
name = "routing"
[env.production.triggers]
crons = ["*/30 * * * *"]

# The necessary secrets are:
# - ETH_NODE
# - GOERLI_NODE
# - BSC_NODE
# - BSC_TESTNET_NODE
# - ETHERLINK_NODE
# - ETHERLINK_TESTNET_NODE
# - NODE_REAL_SUBGRAPH_API_KEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
